version: 2.1
jobs:
  build:
    machine:
      image: 'ubuntu-2004:202010-01'
    steps:
      - checkout
      - run:
          name: Install linux support apps
          command: |
            sudo apt-get install docker
            sudo apt-get install make
            sudo apt-get install git
            git --version
